-- 7.

SELECT naam, spelersnr, (SELECT COUNT(*) FROM Boetes WHERE SPELERSNR = s.SPELERSNR) AS aantalboetes,
(SELECT COUNT(*) FROM WEDSTRIJDEN WHERE SPELERSNR = s.SPELERSNR) AS aantalwedstrijden
FROM Spelers s
WHERE (SELECT COUNT(*) FROM Boetes WHERE SPELERSNR = s.SPELERSNR) >
(SELECT COUNT(*) FROM WEDSTRIJDEN WHERE SPELERSNR = s.SPELERSNR)